theme: forty_jekyll_theme
remote_theme: andrewbanchich/forty-jekyll-theme

title: "Jeshua Lin"
description: "test"
email: "jlin025@e.ntu.edu.sg"
telegram: "jeslinmx"
github_url: "https://github.com/jeslinmx"
tiles-source: "pages"

exclude: ["README", "TODO"]